version: '3'
vars:
  DLR: curl
  DLR_FLAGS: "-L"
  ALPINE_REL: "3.20"
  ALPINE_VER: "3.20.2"
  ALPINE_ARCH: "x86_64"
  ALPINE_CDN: dl-cdn.alpinelinux.org
  ALPINE_MIRROR: mirrors.aliyun.com
  BASE_URL: "https://{{.ALPINE_MIRROR}}/alpine/v{{.ALPINE_REL}}/releases/x86_64/alpine-minirootfs-{{.ALPINE_VER}}-{{.ALPINE_ARCH}}.tar.gz"

tasks:
  default:
    cmds:
      - task: clean
      - task: build
  build:
    desc: "构建一个为WSL环境定制的Alpine Linux根文件系统包"
    deps: [base]
    cmds:
      - task: profile
      - "echo -e '\\e[1;31mBuilding rootfs...\\e[m'"
      - sudo mkdir rootfs
      - "sudo tar -zxpf base.tar.gz -C rootfs"
      - "echo -en 'nameserver 114.114.115.115\nnameserver 9.9.9.9\n' | sudo tee rootfs/etc/resolv.conf"
      - "sudo cp -f profile rootfs/etc/profile"
      - sudo chroot rootfs /bin/sed -i 's|{{.ALPINE_CDN}}|{{.ALPINE_MIRROR}}|g' /etc/apk/repositories
      - sudo chroot rootfs /sbin/apk update
      - sudo chroot rootfs /sbin/apk upgrade
      - sudo chroot rootfs /sbin/apk add bash vim curl wget htop tree xz zip unzip
      - "echo '# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line.' | sudo tee rootfs/etc/resolv.conf"
      - "sudo rm -rf `find rootfs/var/cache/apk/ -type f`"
      - "sudo chmod +x rootfs"
      - "echo -e '\\e[1;31mBuilding rootfs.tar.gz...\\e[m'"
      - "sudo tar -zcpf ./dist/rootfs.tar.gz -C ./rootfs ."
      - "sudo chown `id -un` ./dist/rootfs.tar.gz"
  container:
    desc: "把制作的根文件系统导入到podman镜像库中"
    cmds:
      - podman manifest create alpine-base
      - podman build --platform linux/amd64 --manifest alpine-base --tag alpine:latest .
      - podman manifest inspect alpine-base
      - podman image prune -f
  clean:
    desc: "删除中间产生的临时文件"
    cmds:
      - sudo rm -f base.tar.gz
      - sudo rm -f profile
      - sudo rm -rf rootfs
  base:
    desc: "下载一个Alpine Linux指定版本的mini rootfs压缩包作为基础的rootfs树"
    cmds:
      - "echo -e '\\e[1;31mDownloading base.tar.gz...\\e[m'"
      - "{{.DLR}} {{.DLR_FLAGS}} {{.BASE_URL}} -o base.tar.gz"
  profile:
    cmds:
      - |
        cat > profile <<'EOF'
        export CHARSET=UTF-8
        export LANG=C.UTF-8
        export PAGER=less
        export PS1='\\h:\\w \\\$ '
        umask 022

        for script in /etc/profile.d/*.sh ; do
          if [ -r \\$script ] ; then
            . \\$script
          fi
        done
        EOF

